version: '3'

services:
  inference:
    container_name: worker-10m-inference
    build:
      context: .
    ports:
      - "8011:8011"
    networks:
      net1-worker1:
        aliases:
          - inference
        ipv4_address: 172.31.0.2
    healthcheck:
      # test: ["CMD", "curl", "-f", "http://localhost:8011/inference/ETH"]
      test: ["CMD-SHELL", "curl -f http://localhost:8011/inference/ETH || exit 1 && curl -f http://localhost:8011/inference/BTC || exit 1 && curl -f http://localhost:8011/inference/SOL || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 300s
    volumes:
      - ./inference-data:/app/data
    restart: unless-stopped
  
  updater:
    container_name: worker-10m-updater
    build: .
    environment:
      - INFERENCE_API_ADDRESS=http://inference:8011
    command: >
      sh -c "
      while true; do
        python -u /app/update_app.py;
        sleep 300;  # 300 seconds (5 minutes)
      done
      "
    depends_on:
      inference:
        condition: service_healthy
    networks:
      net1-worker1:
        aliases:
          - updater
        ipv4_address: 172.31.0.3
    restart: unless-stopped
    
  allora-topic-01:
    container_name: allora-topic-01
    environment:
      - INFERENCE_API_ADDRESS=http://inference:8011
      - HOME=/data
      - BOOT_NODES_URL=https://raw.githubusercontent.com/allora-network/networks/main/allora-testnet-1/heads.txt
      - ALLORA_RPC=https://allora-rpc.testnet-1.testnet.allora.network/
    build:
      context: .
      dockerfile: Dockerfile_b7s
    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        set -ex
        # Define my public IP for dialback address
        MY_IP=$(curl -4 icanhazip.com)

        if [ ! -f /data/keys/priv.bin ]; then
          echo "Generating new private keys..."
          mkdir -p /data/keys
          cd /data/keys
          allora-keys
        fi
        allora-node --role=worker \
          --peer-db=/data/peerdb \
          --function-db=/data/function-db \
          --runtime-path=/app/runtime \
          --runtime-cli=bls-runtime \
          --workspace=/data/workspace \
          --private-key=/data/keys/priv.bin \
          --log-level=debug \
          --port=9101 \
          --allora-chain-home-dir=/data/.allorad \
          --dialback-address=$${MY_IP} \
          --dialback-port=9101 \
          --boot-nodes=$(curl -Ls $${BOOT_NODES_URL}) \
          --topic=allora-topic-1-worker \
          --allora-chain-key-name=allora-topic-01 \
          --allora-chain-restore-mnemonic='[SEED PHASE]' \
          --allora-chain-topic-id=1 \
          --allora-node-rpc-address=$${ALLORA_RPC} \
          --allora-chain-worker-mode=worker
    volumes:
      - ./worker-topic-1-data:/data
    working_dir: /data
    depends_on:
      - inference
    ports:
      - "9101:9101"
    networks:
      net1-worker1:
        aliases:
          - worker_topic_1
        ipv4_address: 172.31.0.21
    restart: unless-stopped

  allora-topic-03:
    container_name: allora-topic-03
    environment:
      - INFERENCE_API_ADDRESS=http://inference:8011
      - HOME=/data
      - BOOT_NODES_URL=https://raw.githubusercontent.com/allora-network/networks/main/allora-testnet-1/heads.txt
      - ALLORA_RPC=https://allora-rpc.testnet-1.testnet.allora.network/
    build:
      context: .
      dockerfile: Dockerfile_b7s
    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        set -ex
        # Define my public IP for dialback address
        MY_IP=$(curl -4 icanhazip.com)

        if [ ! -f /data/keys/priv.bin ]; then
          echo "Generating new private keys..."
          mkdir -p /data/keys
          cd /data/keys
          allora-keys
        fi
        allora-node --role=worker \
          --peer-db=/data/peerdb \
          --function-db=/data/function-db \
          --runtime-path=/app/runtime \
          --runtime-cli=bls-runtime \
          --workspace=/data/workspace \
          --private-key=/data/keys/priv.bin \
          --log-level=debug \
          --port=9103 \
          --allora-chain-home-dir=/data/.allorad \
          --dialback-address=$${MY_IP} \
          --dialback-port=9103 \
          --boot-nodes=$(curl -Ls $${BOOT_NODES_URL}) \
          --topic=allora-topic-3-worker \
          --allora-chain-key-name=allora-topic-03 \
          --allora-chain-restore-mnemonic='[SEED PHASE]' \
          --allora-chain-topic-id=3 \
          --allora-node-rpc-address=$${ALLORA_RPC} \
          --allora-chain-worker-mode=worker
    volumes:
      - ./worker-topic-3-data:/data
    working_dir: /data
    depends_on:
      - inference
    ports:
      - "9103:9103"
    networks:
      net1-worker1:
        aliases:
          - worker_topic_3
        ipv4_address: 172.31.0.23
    restart: unless-stopped

  allora-topic-05:
    container_name: allora-topic-05
    environment:
      - INFERENCE_API_ADDRESS=http://inference:8011
      - HOME=/data
      - BOOT_NODES_URL=https://raw.githubusercontent.com/allora-network/networks/main/allora-testnet-1/heads.txt
      - ALLORA_RPC=https://allora-rpc.testnet-1.testnet.allora.network/
    build:
      context: .
      dockerfile: Dockerfile_b7s
    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        set -ex
        # Define my public IP for dialback address
        MY_IP=$(curl -4 icanhazip.com)

        if [ ! -f /data/keys/priv.bin ]; then
          echo "Generating new private keys..."
          mkdir -p /data/keys
          cd /data/keys
          allora-keys
        fi
        allora-node --role=worker \
          --peer-db=/data/peerdb \
          --function-db=/data/function-db \
          --runtime-path=/app/runtime \
          --runtime-cli=bls-runtime \
          --workspace=/data/workspace \
          --private-key=/data/keys/priv.bin \
          --log-level=debug \
          --port=9105 \
          --allora-chain-home-dir=/data/.allorad \
          --dialback-address=$${MY_IP} \
          --dialback-port=9105 \
          --boot-nodes=$(curl -Ls $${BOOT_NODES_URL}) \
          --topic=allora-topic-5-worker \
          --allora-chain-key-name=allora-topic-05 \
          --allora-chain-restore-mnemonic='[SEED PHASE]' \
          --allora-chain-topic-id=5 \
          --allora-node-rpc-address=$${ALLORA_RPC} \
          --allora-chain-worker-mode=worker
    volumes:
      - ./worker-topic-5-data:/data
    working_dir: /data
    depends_on:
      - inference
    ports:
      - "9105:9105"
    networks:
      net1-worker1:
        aliases:
          - worker_topic_5
        ipv4_address: 172.31.0.25
    restart: unless-stopped
  
networks:
  net1-worker1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/24

volumes:
  inference-data:
  worker-topic-1-data:
  worker-topic-3-data:
  worker-topic-5-data: