version: '3'

services:
  inference:
    container_name: worker-24h-inference
    build:
      context: .
    ports:
      - "8010:8010"
    networks:
      net1-worker2:
        aliases:
          - inference
        ipv4_address: 172.32.0.2
    restart: unless-stopped
    
  allora-topic-02:
    container_name: allora-topic-02
    environment:
      - INFERENCE_API_ADDRESS=http://inference:8010
      - HOME=/data
      - BOOT_NODES_URL=https://raw.githubusercontent.com/allora-network/networks/main/allora-testnet-1/heads.txt
      - ALLORA_RPC=https://allora-rpc.testnet-1.testnet.allora.network/
    build:
      context: .
      dockerfile: Dockerfile_b7s
    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        set -ex
        # Define my public IP for dialback address
        MY_IP=$(curl -4 icanhazip.com)

        if [ ! -f /data/keys/priv.bin ]; then
          echo "Generating new private keys..."
          mkdir -p /data/keys
          cd /data/keys
          allora-keys
        fi
        allora-node --role=worker \
          --peer-db=/data/peerdb \
          --function-db=/data/function-db \
          --runtime-path=/app/runtime --runtime-cli=bls-runtime \
          --workspace=/data/workspace \
          --private-key=/data/keys/priv.bin \
          --log-level=debug \
          --port=9102 \
          --dialback-address=$${MY_IP} \
          --dialback-port=9102 \
          --boot-nodes=$(curl -Ls $${BOOT_NODES_URL}) \
          --topic=allora-topic-2-worker \
          --allora-chain-key-name=allora-topic-02 \
          --allora-chain-restore-mnemonic='[SEED PHASE]' \
          --allora-chain-topic-id=2 \
          --allora-node-rpc-address=$${ALLORA_RPC} \
          --allora-chain-worker-mode=worker
    volumes:
      - ./worker-topic-2-data:/data
    working_dir: /data
    depends_on:
      - inference
    ports:
      - "9102:9102"
    networks:
      net1-worker2:
        aliases:
          - worker_topic_2
        ipv4_address: 172.32.0.21
    restart: unless-stopped

  allora-topic-04:
    container_name: allora-topic-04
    environment:
      - INFERENCE_API_ADDRESS=http://inference:8010
      - HOME=/data
      - BOOT_NODES_URL=https://raw.githubusercontent.com/allora-network/networks/main/allora-testnet-1/heads.txt
      - ALLORA_RPC=https://allora-rpc.testnet-1.testnet.allora.network/
    build:
      context: .
      dockerfile: Dockerfile_b7s
    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        set -ex
        # Define my public IP for dialback address
        MY_IP=$(curl -4 icanhazip.com)

        if [ ! -f /data/keys/priv.bin ]; then
          echo "Generating new private keys..."
          mkdir -p /data/keys
          cd /data/keys
          allora-keys
        fi
        allora-node --role=worker \
          --peer-db=/data/peerdb \
          --function-db=/data/function-db \
          --runtime-path=/app/runtime \
          --runtime-cli=bls-runtime \
          --workspace=/data/workspace \
          --private-key=/data/keys/priv.bin \
          --log-level=debug \
          --port=9104 \
          --dialback-address=$${MY_IP} \
          --dialback-port=9104 \
          --boot-nodes=$(curl -Ls $${BOOT_NODES_URL}) \
          --topic=allora-topic-4-worker \
          --allora-chain-key-name=allora-topic-04 \
          --allora-chain-restore-mnemonic='[SEED PHASE]' \
          --allora-chain-topic-id=4 \
          --allora-node-rpc-address=$${ALLORA_RPC} \
          --allora-chain-worker-mode=worker
    volumes:
      - ./worker-topic-4-data:/data
    working_dir: /data
    depends_on:
      - inference
    ports:
      - "9104:9104"
    networks:
      net1-worker2:
        aliases:
          - worker_topic_4
        ipv4_address: 172.32.0.23
    restart: unless-stopped

  allora-topic-06:
    container_name: allora-topic-06
    environment:
      - INFERENCE_API_ADDRESS=http://inference:8010
      - HOME=/data
      - BOOT_NODES_URL=https://raw.githubusercontent.com/allora-network/networks/main/allora-testnet-1/heads.txt
      - ALLORA_RPC=https://allora-rpc.testnet-1.testnet.allora.network/
    build:
      context: .
      dockerfile: Dockerfile_b7s
    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        set -ex
        # Define my public IP for dialback address
        MY_IP=$(curl -4 icanhazip.com)

        if [ ! -f /data/keys/priv.bin ]; then
          echo "Generating new private keys..."
          mkdir -p /data/keys
          cd /data/keys
          allora-keys
        fi
        allora-node --role=worker \
          --peer-db=/data/peerdb \
          --function-db=/data/function-db \
          --runtime-path=/app/runtime \
          --runtime-cli=bls-runtime \
          --workspace=/data/workspace \
          --private-key=/data/keys/priv.bin \
          --log-level=debug \
          --port=9106 \
          --dialback-address=$${MY_IP} \
          --dialback-port=9106 \
          --boot-nodes=$(curl -Ls $${BOOT_NODES_URL}) \
          --topic=allora-topic-6-worker \
          --allora-chain-key-name=allora-topic-06 \
          --allora-chain-restore-mnemonic='[SEED PHASE]' \
          --allora-chain-topic-id=6 \
          --allora-node-rpc-address=$${ALLORA_RPC} \
          --allora-chain-worker-mode=worker
    volumes:
      - ./worker-topic-6-data:/data
    working_dir: /data
    depends_on:
      - inference
    ports:
      - "9106:9106"
    networks:
      net1-worker2:
        aliases:
          - worker_topic_6
        ipv4_address: 172.32.0.25
    restart: unless-stopped
  
networks:
  net1-worker2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.32.0.0/24

volumes:
  inference-data:
  worker-topic-2-data:
  worker-topic-4-data:
  worker-topic-6-data: