version: '3'

services:
  inference:
    container_name: worker-20m-inference
    build:
      context: .
    ports:
      - "8012:8012"
    networks:
      net1-worker3:
        aliases:
          - inference
        ipv4_address: 172.33.0.2
    healthcheck:
      # test: ["CMD", "curl", "-f", "http://localhost:8011/inference/ETH"]
      test: ["CMD-SHELL", "curl -f http://localhost:8012/inference/ETH || exit 1 && curl -f http://localhost:8012/inference/BNB || exit 1 && curl -f http://localhost:8012/inference/ARB || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 300s
    volumes:
      - ./inference-data:/app/data
    restart: unless-stopped
  
  updater:
    container_name: worker-20m-updater
    build: .
    environment:
      - INFERENCE_API_ADDRESS=http://inference:8012
    command: >
      sh -c "
      while true; do
        python -u /app/update_app.py;
        sleep 900;  # 900 seconds (15 minutes)
      done
      "
    depends_on:
      inference:
        condition: service_healthy
    networks:
      net1-worker3:
        aliases:
          - updater
        ipv4_address: 172.33.0.3
    restart: unless-stopped
    
  allora-topic-07:
    container_name: allora-topic-07
    environment:
      - INFERENCE_API_ADDRESS=http://inference:8012
      - HOME=/data
      - BOOT_NODES_URL=https://raw.githubusercontent.com/allora-network/networks/main/allora-testnet-1/heads.txt
      - ALLORA_RPC=https://allora-rpc.testnet-1.testnet.allora.network/
    build:
      context: .
      dockerfile: Dockerfile_b7s
    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        set -ex
        # Define my public IP for dialback address
        MY_IP=$(curl -4 icanhazip.com)

        if [ ! -f /data/keys/priv.bin ]; then
          echo "Generating new private keys..."
          mkdir -p /data/keys
          cd /data/keys
          allora-keys
        fi
        allora-node --role=worker --peer-db=/data/peerdb \
        --function-db=/data/function-db \
          --runtime-path=/app/runtime \
          --runtime-cli=bls-runtime \
          --workspace=/data/workspace \
          --private-key=/data/keys/priv.bin \
          --log-level=debug \
          --port=9107 \
          --allora-chain-home-dir=/data/.allorad \
          --dialback-address=$${MY_IP} \
          --dialback-port=9107 \
          --boot-nodes=$(curl -Ls $${BOOT_NODES_URL}) \
          --topic=allora-topic-7-worker \
          --allora-chain-key-name=allora-topic-07 \
          --allora-chain-restore-mnemonic='[SEED PHASE]' \
          --allora-chain-topic-id=7 \
          --allora-node-rpc-address=$${ALLORA_RPC} \
          --allora-chain-worker-mode=worker
    volumes:
      - ./worker-topic-7-data:/data
    working_dir: /data
    depends_on:
      - inference
    ports:
      - "9107:9107"
    networks:
      net1-worker3:
        aliases:
          - worker_topic_7
        ipv4_address: 172.33.0.21
    restart: unless-stopped

  allora-topic-08:
    container_name: allora-topic-08
    environment:
      - INFERENCE_API_ADDRESS=http://inference:8012
      - HOME=/data
      - BOOT_NODES_URL=https://raw.githubusercontent.com/allora-network/networks/main/allora-testnet-1/heads.txt
      - ALLORA_RPC=https://allora-rpc.testnet-1.testnet.allora.network/
    build:
      context: .
      dockerfile: Dockerfile_b7s
    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        set -ex
        # Define my public IP for dialback address
        MY_IP=$(curl -4 icanhazip.com)

        if [ ! -f /data/keys/priv.bin ]; then
          echo "Generating new private keys..."
          mkdir -p /data/keys
          cd /data/keys
          allora-keys
        fi
        allora-node --role=worker \
          --peer-db=/data/peerdb \
          --function-db=/data/function-db \
          --runtime-path=/app/runtime \
          --runtime-cli=bls-runtime \
          --workspace=/data/workspace \
          --private-key=/data/keys/priv.bin \
          --log-level=debug \
          --port=9108 \
          --allora-chain-home-dir=/data/.allorad \
          --dialback-address=$${MY_IP} \
          --dialback-port=9108 \
          --boot-nodes=$(curl -Ls $${BOOT_NODES_URL}) \
          --topic=allora-topic-8-worker \
          --allora-chain-key-name=allora-topic-08 \
          --allora-chain-restore-mnemonic='[SEED PHASE]' \
          --allora-chain-topic-id=8 \
          --allora-node-rpc-address=$${ALLORA_RPC} \
          --allora-chain-worker-mode=worker
    volumes:
      - ./worker-topic-8-data:/data
    working_dir: /data
    depends_on:
      - inference
    ports:
      - "9108:9108"
    networks:
      net1-worker3:
        aliases:
          - worker_topic_3
        ipv4_address: 172.33.0.23
    restart: unless-stopped

  allora-topic-09:
    container_name: allora-topic-09
    environment:
      - INFERENCE_API_ADDRESS=http://inference:8012
      - HOME=/data
      - BOOT_NODES_URL=https://raw.githubusercontent.com/allora-network/networks/main/allora-testnet-1/heads.txt
      - ALLORA_RPC=https://allora-rpc.testnet-1.testnet.allora.network/
    build:
      context: .
      dockerfile: Dockerfile_b7s
    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        set -ex
        # Define my public IP for dialback address
        MY_IP=$(curl -4 icanhazip.com)

        if [ ! -f /data/keys/priv.bin ]; then
          echo "Generating new private keys..."
          mkdir -p /data/keys
          cd /data/keys
          allora-keys
        fi
        allora-node --role=worker \
          --peer-db=/data/peerdb \
          --function-db=/data/function-db \
          --runtime-path=/app/runtime \
          --runtime-cli=bls-runtime \
          --workspace=/data/workspace \
          --private-key=/data/keys/priv.bin \
          --log-level=debug \
          --port=9109 \
          --allora-chain-home-dir=/data/.allorad \
          --dialback-address=$${MY_IP} \
          --dialback-port=9109 \
          --boot-nodes=$(curl -Ls $${BOOT_NODES_URL}) \
          --topic=allora-topic-9-worker \
          --allora-chain-key-name=allora-topic-09 \
          --allora-chain-restore-mnemonic='[SEED PHASE]' \
          --allora-chain-topic-id=9 \
          --allora-node-rpc-address=$${ALLORA_RPC} \
          --allora-chain-worker-mode=worker
    volumes:
      - ./worker-topic-9-data:/data
    working_dir: /data
    depends_on:
      - inference
    ports:
      - "9109:9109"
    networks:
      net1-worker3:
        aliases:
          - worker_topic_9
        ipv4_address: 172.33.0.25
    restart: unless-stopped
  
networks:
  net1-worker3:
    driver: bridge
    ipam:
      config:
        - subnet: 172.33.0.0/24

volumes:
  inference-data:
  worker-topic-7-data:
  worker-topic-8-data:
  worker-topic-9-data: