version: '3'

services:
  inference:
    container_name: net1-worker4-inference
    build:
      context: .
    command: python -u /app/app.py
    ports:
      - "8013:8013"
    networks:
      net1-worker4:
        aliases:
          - inference
        ipv4_address: 172.34.0.2
    healthcheck:
      # test: ["CMD", "curl", "-f", "http://localhost:8010/inference/ETH"] "BOME", "BOND", "DOGE", "WIF", "MEW", "MEME"
      test: ["CMD-SHELL", "curl -f http://localhost:8010/inference/BOME || exit 1 && curl -f http://localhost:8010/inference/BOND || exit 1 && curl -f http://localhost:8010/inference/DOGE || exit 1 && curl -f http://localhost:8010/inference/WIF || exit 1 && curl -f http://localhost:8010/inference/MEW || exit 1 && curl -f http://localhost:8010/inference/MEME || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 300s
    volumes:
      - ./inference-data:/app/data
  
  updater:
    container_name: net1-updater4
    build: .
    environment:
      - INFERENCE_API_ADDRESS=http://inference:8013
    command: >
      sh -c "
      while true; do
        python -u /app/update_app.py;
        sleep 12h;
      done
      "
    depends_on:
      inference:
        condition: service_healthy
    networks:
      net1-worker4:
        aliases:
          - updater
        ipv4_address: 172.34.0.3
    
  allora-topic-10:
    container_name: allora-topic-10
    environment:
      - INFERENCE_API_ADDRESS=http://inference:8013
      - HOME=/data
    build:
      context: .
      dockerfile: Dockerfile_b7s
    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        if [ ! -f /data/keys/priv.bin ]; then
          echo "Generating new private keys..."
          mkdir -p /data/keys
          cd /data/keys
          allora-keys
        fi
        allora-node --role=worker --peer-db=/data/peerdb --function-db=/data/function-db \
          --runtime-path=/app/runtime --runtime-cli=bls-runtime --workspace=/data/workspace \
          --private-key=/data/keys/priv.bin --log-level=debug --port=9110 \
          --boot-nodes=/dns/head-0-p2p.testnet-1.testnet.allora.network/tcp/32130/p2p/12D3KooWLBhsSucVVcyVCaM9pvK8E7tWBM9L19s7XQHqqejyqgEC,/dns/head-1-p2p.testnet-1.testnet.allora.network/tcp/32131/p2p/12D3KooWEUNWg7YHeeCtH88ju63RBfY5hbdv9hpv84ffEZpbJszt,/dns/head-2-p2p.testnet-1.testnet.allora.network/tcp/32132/p2p/12D3KooWATfUSo95wtZseHbogpckuFeSvpL4yks6XtvrjVHcCCXk,/dns/head-5-p2p.testnet-1.testnet.allora.network/tcp/32135/p2p/12D3KooWAazxKoYszYt4XhCrGWoEUyAFMaU7DB9RZ8TsA7qwLfin,/dns/head-4-p2p.testnet-1.testnet.allora.network/tcp/32134/p2p/12D3KooWRF8HNU21AukE7KC6kZqxqvCiZ5nM9xcLW4YvsuGAYbcm,/dns/head-3-p2p.testnet-1.testnet.allora.network/tcp/32133/p2p/12D3KooWDrArwBSCNxwL3mgJ2NaUygdtPtiwVQtPJafyAH6FSiUf \
          --topic=allora-topic-10-worker \
          --allora-chain-key-name=allora-topic-10 \
          --allora-chain-restore-mnemonic='[SEED PHASE]' \
          --allora-chain-topic-id=10 \
          --allora-node-rpc-address=https://allora-rpc.testnet-1.testnet.allora.network \
          --allora-chain-worker-mode=worker
    volumes:
      - ./worker-topic-10-data:/data
    working_dir: /data
    depends_on:
      - inference
    ports:
      - "9110:9110"
    networks:
      net1-worker4:
        aliases:
          - allora-topic-10
        ipv4_address: 172.34.0.21
networks:
  net1-worker4:
    driver: bridge
    ipam:
      config:
        - subnet: 172.34.0.0/24

volumes:
  inference-data:
  worker-topic-10-data: